//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("UberProf.BackendModel", "FK318A099B6965C307", "Buyers", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Migration.Buyer), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Migration.Order), true)]
[assembly: EdmRelationshipAttribute("UberProf.BackendModel", "FK570785C186B03BAA", "Buyers", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Migration.Buyer), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Migration.Order), true)]
[assembly: EdmRelationshipAttribute("UberProf.BackendModel", "FK3A420F9C52F8CEC2", "Freebies", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Migration.Freebie), "LicenseFiles", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Migration.LicenseFile), true)]
[assembly: EdmRelationshipAttribute("UberProf.BackendModel", "FK3A420F9C2AB61060", "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Migration.Order), "LicenseFiles", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Migration.LicenseFile), true)]

#endregion

namespace Migration
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Buyer> Buyers
        {
            get
            {
                if ((_Buyers == null))
                {
                    _Buyers = base.CreateObjectSet<Buyer>("Buyers");
                }
                return _Buyers;
            }
        }
        private ObjectSet<Buyer> _Buyers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Download> Downloads
        {
            get
            {
                if ((_Downloads == null))
                {
                    _Downloads = base.CreateObjectSet<Download>("Downloads");
                }
                return _Downloads;
            }
        }
        private ObjectSet<Download> _Downloads;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ErrorReport> ErrorReports
        {
            get
            {
                if ((_ErrorReports == null))
                {
                    _ErrorReports = base.CreateObjectSet<ErrorReport>("ErrorReports");
                }
                return _ErrorReports;
            }
        }
        private ObjectSet<ErrorReport> _ErrorReports;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Freebie> Freebies
        {
            get
            {
                if ((_Freebies == null))
                {
                    _Freebies = base.CreateObjectSet<Freebie>("Freebies");
                }
                return _Freebies;
            }
        }
        private ObjectSet<Freebie> _Freebies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LicenseFile> LicenseFiles
        {
            get
            {
                if ((_LicenseFiles == null))
                {
                    _LicenseFiles = base.CreateObjectSet<LicenseFile>("LicenseFiles");
                }
                return _LicenseFiles;
            }
        }
        private ObjectSet<LicenseFile> _LicenseFiles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Order> Orders
        {
            get
            {
                if ((_Orders == null))
                {
                    _Orders = base.CreateObjectSet<Order>("Orders");
                }
                return _Orders;
            }
        }
        private ObjectSet<Order> _Orders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Prospect> Prospects
        {
            get
            {
                if ((_Prospects == null))
                {
                    _Prospects = base.CreateObjectSet<Prospect>("Prospects");
                }
                return _Prospects;
            }
        }
        private ObjectSet<Prospect> _Prospects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Trial> Trials
        {
            get
            {
                if ((_Trials == null))
                {
                    _Trials = base.CreateObjectSet<Trial>("Trials");
                }
                return _Trials;
            }
        }
        private ObjectSet<Trial> _Trials;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Buyers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBuyers(Buyer buyer)
        {
            base.AddObject("Buyers", buyer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Downloads EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDownloads(Download download)
        {
            base.AddObject("Downloads", download);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ErrorReports EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToErrorReports(ErrorReport errorReport)
        {
            base.AddObject("ErrorReports", errorReport);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Freebies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFreebies(Freebie freebie)
        {
            base.AddObject("Freebies", freebie);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LicenseFiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLicenseFiles(LicenseFile licenseFile)
        {
            base.AddObject("LicenseFiles", licenseFile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Orders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrders(Order order)
        {
            base.AddObject("Orders", order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Prospects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProspects(Prospect prospect)
        {
            base.AddObject("Prospects", prospect);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Trials EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTrials(Trial trial)
        {
            base.AddObject("Trials", trial);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UberProf.BackendModel", Name="Buyer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Buyer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Buyer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Buyer CreateBuyer(global::System.Int64 id)
        {
            Buyer buyer = new Buyer();
            buyer.Id = id;
            return buyer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactEmail
        {
            get
            {
                return _ContactEmail;
            }
            set
            {
                OnContactEmailChanging(value);
                ReportPropertyChanging("ContactEmail");
                _ContactEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactEmail");
                OnContactEmailChanged();
            }
        }
        private global::System.String _ContactEmail;
        partial void OnContactEmailChanging(global::System.String value);
        partial void OnContactEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactLastName
        {
            get
            {
                return _ContactLastName;
            }
            set
            {
                OnContactLastNameChanging(value);
                ReportPropertyChanging("ContactLastName");
                _ContactLastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactLastName");
                OnContactLastNameChanged();
            }
        }
        private global::System.String _ContactLastName;
        partial void OnContactLastNameChanging(global::System.String value);
        partial void OnContactLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactFirstName
        {
            get
            {
                return _ContactFirstName;
            }
            set
            {
                OnContactFirstNameChanging(value);
                ReportPropertyChanging("ContactFirstName");
                _ContactFirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactFirstName");
                OnContactFirstNameChanged();
            }
        }
        private global::System.String _ContactFirstName;
        partial void OnContactFirstNameChanging(global::System.String value);
        partial void OnContactFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IpAddress
        {
            get
            {
                return _IpAddress;
            }
            set
            {
                OnIpAddressChanging(value);
                ReportPropertyChanging("IpAddress");
                _IpAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IpAddress");
                OnIpAddressChanged();
            }
        }
        private global::System.String _IpAddress;
        partial void OnIpAddressChanging(global::System.String value);
        partial void OnIpAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactPhone
        {
            get
            {
                return _ContactPhone;
            }
            set
            {
                OnContactPhoneChanging(value);
                ReportPropertyChanging("ContactPhone");
                _ContactPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactPhone");
                OnContactPhoneChanged();
            }
        }
        private global::System.String _ContactPhone;
        partial void OnContactPhoneChanging(global::System.String value);
        partial void OnContactPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactAlternativeMail
        {
            get
            {
                return _ContactAlternativeMail;
            }
            set
            {
                OnContactAlternativeMailChanging(value);
                ReportPropertyChanging("ContactAlternativeMail");
                _ContactAlternativeMail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactAlternativeMail");
                OnContactAlternativeMailChanged();
            }
        }
        private global::System.String _ContactAlternativeMail;
        partial void OnContactAlternativeMailChanging(global::System.String value);
        partial void OnContactAlternativeMailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address2
        {
            get
            {
                return _Address2;
            }
            set
            {
                OnAddress2Changing(value);
                ReportPropertyChanging("Address2");
                _Address2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address2");
                OnAddress2Changed();
            }
        }
        private global::System.String _Address2;
        partial void OnAddress2Changing(global::System.String value);
        partial void OnAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address1
        {
            get
            {
                return _Address1;
            }
            set
            {
                OnAddress1Changing(value);
                ReportPropertyChanging("Address1");
                _Address1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address1");
                OnAddress1Changed();
            }
        }
        private global::System.String _Address1;
        partial void OnAddress1Changing(global::System.String value);
        partial void OnAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyName
        {
            get
            {
                return _CompanyName;
            }
            set
            {
                OnCompanyNameChanging(value);
                ReportPropertyChanging("CompanyName");
                _CompanyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyName");
                OnCompanyNameChanged();
            }
        }
        private global::System.String _CompanyName;
        partial void OnCompanyNameChanging(global::System.String value);
        partial void OnCompanyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZipPostalCode
        {
            get
            {
                return _ZipPostalCode;
            }
            set
            {
                OnZipPostalCodeChanging(value);
                ReportPropertyChanging("ZipPostalCode");
                _ZipPostalCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZipPostalCode");
                OnZipPostalCodeChanged();
            }
        }
        private global::System.String _ZipPostalCode;
        partial void OnZipPostalCodeChanging(global::System.String value);
        partial void OnZipPostalCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StateProvince
        {
            get
            {
                return _StateProvince;
            }
            set
            {
                OnStateProvinceChanging(value);
                ReportPropertyChanging("StateProvince");
                _StateProvince = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StateProvince");
                OnStateProvinceChanged();
            }
        }
        private global::System.String _StateProvince;
        partial void OnStateProvinceChanging(global::System.String value);
        partial void OnStateProvinceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("UberProf.BackendModel", "FK318A099B6965C307", "Orders")]
        public EntityCollection<Order> Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("UberProf.BackendModel.FK318A099B6965C307", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("UberProf.BackendModel.FK318A099B6965C307", "Orders", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("UberProf.BackendModel", "FK570785C186B03BAA", "Orders")]
        public EntityCollection<Order> Orders1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("UberProf.BackendModel.FK570785C186B03BAA", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("UberProf.BackendModel.FK570785C186B03BAA", "Orders", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UberProf.BackendModel", Name="Download")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Download : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Download object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="profile">Initial value of the Profile property.</param>
        public static Download CreateDownload(global::System.Int64 id, global::System.String profile)
        {
            Download download = new Download();
            download.Id = id;
            download.Profile = profile;
            return download;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> TrackingId
        {
            get
            {
                return _TrackingId;
            }
            set
            {
                OnTrackingIdChanging(value);
                ReportPropertyChanging("TrackingId");
                _TrackingId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TrackingId");
                OnTrackingIdChanged();
            }
        }
        private Nullable<global::System.Guid> _TrackingId;
        partial void OnTrackingIdChanging(Nullable<global::System.Guid> value);
        partial void OnTrackingIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> At
        {
            get
            {
                return _At;
            }
            set
            {
                OnAtChanging(value);
                ReportPropertyChanging("At");
                _At = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("At");
                OnAtChanged();
            }
        }
        private Nullable<global::System.DateTime> _At;
        partial void OnAtChanging(Nullable<global::System.DateTime> value);
        partial void OnAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Profile
        {
            get
            {
                return _Profile;
            }
            set
            {
                OnProfileChanging(value);
                ReportPropertyChanging("Profile");
                _Profile = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Profile");
                OnProfileChanged();
            }
        }
        private global::System.String _Profile;
        partial void OnProfileChanging(global::System.String value);
        partial void OnProfileChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UberProf.BackendModel", Name="ErrorReport")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ErrorReport : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ErrorReport object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="profile">Initial value of the Profile property.</param>
        public static ErrorReport CreateErrorReport(global::System.Guid id, global::System.String profile)
        {
            ErrorReport errorReport = new ErrorReport();
            errorReport.Id = id;
            errorReport.Profile = profile;
            return errorReport;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OperationSystem
        {
            get
            {
                return _OperationSystem;
            }
            set
            {
                OnOperationSystemChanging(value);
                ReportPropertyChanging("OperationSystem");
                _OperationSystem = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OperationSystem");
                OnOperationSystemChanged();
            }
        }
        private global::System.String _OperationSystem;
        partial void OnOperationSystemChanging(global::System.String value);
        partial void OnOperationSystemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> WorkingSet
        {
            get
            {
                return _WorkingSet;
            }
            set
            {
                OnWorkingSetChanging(value);
                ReportPropertyChanging("WorkingSet");
                _WorkingSet = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WorkingSet");
                OnWorkingSetChanged();
            }
        }
        private Nullable<global::System.Int64> _WorkingSet;
        partial void OnWorkingSetChanging(Nullable<global::System.Int64> value);
        partial void OnWorkingSetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProcessorCount
        {
            get
            {
                return _ProcessorCount;
            }
            set
            {
                OnProcessorCountChanging(value);
                ReportPropertyChanging("ProcessorCount");
                _ProcessorCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProcessorCount");
                OnProcessorCountChanged();
            }
        }
        private Nullable<global::System.Int32> _ProcessorCount;
        partial void OnProcessorCountChanging(Nullable<global::System.Int32> value);
        partial void OnProcessorCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Guid> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Guid> value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Error
        {
            get
            {
                return _Error;
            }
            set
            {
                OnErrorChanging(value);
                ReportPropertyChanging("Error");
                _Error = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Error");
                OnErrorChanged();
            }
        }
        private global::System.String _Error;
        partial void OnErrorChanging(global::System.String value);
        partial void OnErrorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MachineName
        {
            get
            {
                return _MachineName;
            }
            set
            {
                OnMachineNameChanging(value);
                ReportPropertyChanging("MachineName");
                _MachineName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MachineName");
                OnMachineNameChanged();
            }
        }
        private global::System.String _MachineName;
        partial void OnMachineNameChanging(global::System.String value);
        partial void OnMachineNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ErrorId
        {
            get
            {
                return _ErrorId;
            }
            set
            {
                OnErrorIdChanging(value);
                ReportPropertyChanging("ErrorId");
                _ErrorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ErrorId");
                OnErrorIdChanged();
            }
        }
        private Nullable<global::System.Guid> _ErrorId;
        partial void OnErrorIdChanging(Nullable<global::System.Guid> value);
        partial void OnErrorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Profile
        {
            get
            {
                return _Profile;
            }
            set
            {
                OnProfileChanging(value);
                ReportPropertyChanging("Profile");
                _Profile = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Profile");
                OnProfileChanged();
            }
        }
        private global::System.String _Profile;
        partial void OnProfileChanging(global::System.String value);
        partial void OnProfileChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UberProf.BackendModel", Name="Freebie")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Freebie : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Freebie object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="profile">Initial value of the Profile property.</param>
        public static Freebie CreateFreebie(global::System.Int64 id, global::System.String profile)
        {
            Freebie freebie = new Freebie();
            freebie.Id = id;
            freebie.Profile = profile;
            return freebie;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reason
        {
            get
            {
                return _Reason;
            }
            set
            {
                OnReasonChanging(value);
                ReportPropertyChanging("Reason");
                _Reason = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Reason");
                OnReasonChanged();
            }
        }
        private global::System.String _Reason;
        partial void OnReasonChanging(global::System.String value);
        partial void OnReasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Profile
        {
            get
            {
                return _Profile;
            }
            set
            {
                OnProfileChanging(value);
                ReportPropertyChanging("Profile");
                _Profile = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Profile");
                OnProfileChanged();
            }
        }
        private global::System.String _Profile;
        partial void OnProfileChanging(global::System.String value);
        partial void OnProfileChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("UberProf.BackendModel", "FK3A420F9C52F8CEC2", "LicenseFiles")]
        public EntityCollection<LicenseFile> LicenseFiles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<LicenseFile>("UberProf.BackendModel.FK3A420F9C52F8CEC2", "LicenseFiles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<LicenseFile>("UberProf.BackendModel.FK3A420F9C52F8CEC2", "LicenseFiles", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UberProf.BackendModel", Name="LicenseFile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LicenseFile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LicenseFile object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="profile">Initial value of the Profile property.</param>
        /// <param name="licenseType">Initial value of the LicenseType property.</param>
        public static LicenseFile CreateLicenseFile(global::System.Guid id, global::System.String profile, global::System.String licenseType)
        {
            LicenseFile licenseFile = new LicenseFile();
            licenseFile.Id = id;
            licenseFile.Profile = profile;
            licenseFile.LicenseType = licenseType;
            return licenseFile;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> FreebieId
        {
            get
            {
                return _FreebieId;
            }
            set
            {
                OnFreebieIdChanging(value);
                ReportPropertyChanging("FreebieId");
                _FreebieId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FreebieId");
                OnFreebieIdChanged();
            }
        }
        private Nullable<global::System.Int64> _FreebieId;
        partial void OnFreebieIdChanging(Nullable<global::System.Int64> value);
        partial void OnFreebieIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> OrderId
        {
            get
            {
                return _OrderId;
            }
            set
            {
                OnOrderIdChanging(value);
                ReportPropertyChanging("OrderId");
                _OrderId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderId");
                OnOrderIdChanged();
            }
        }
        private Nullable<global::System.Int64> _OrderId;
        partial void OnOrderIdChanging(Nullable<global::System.Int64> value);
        partial void OnOrderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Profile
        {
            get
            {
                return _Profile;
            }
            set
            {
                OnProfileChanging(value);
                ReportPropertyChanging("Profile");
                _Profile = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Profile");
                OnProfileChanged();
            }
        }
        private global::System.String _Profile;
        partial void OnProfileChanging(global::System.String value);
        partial void OnProfileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LicenseType
        {
            get
            {
                return _LicenseType;
            }
            set
            {
                OnLicenseTypeChanging(value);
                ReportPropertyChanging("LicenseType");
                _LicenseType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LicenseType");
                OnLicenseTypeChanged();
            }
        }
        private global::System.String _LicenseType;
        partial void OnLicenseTypeChanging(global::System.String value);
        partial void OnLicenseTypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("UberProf.BackendModel", "FK3A420F9C52F8CEC2", "Freebies")]
        public Freebie Freebie
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Freebie>("UberProf.BackendModel.FK3A420F9C52F8CEC2", "Freebies").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Freebie>("UberProf.BackendModel.FK3A420F9C52F8CEC2", "Freebies").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Freebie> FreebieReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Freebie>("UberProf.BackendModel.FK3A420F9C52F8CEC2", "Freebies");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Freebie>("UberProf.BackendModel.FK3A420F9C52F8CEC2", "Freebies", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("UberProf.BackendModel", "FK3A420F9C2AB61060", "Orders")]
        public Order Order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("UberProf.BackendModel.FK3A420F9C2AB61060", "Orders").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("UberProf.BackendModel.FK3A420F9C2AB61060", "Orders").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Order> OrderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("UberProf.BackendModel.FK3A420F9C2AB61060", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Order>("UberProf.BackendModel.FK3A420F9C2AB61060", "Orders", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UberProf.BackendModel", Name="Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="profile">Initial value of the Profile property.</param>
        public static Order CreateOrder(global::System.Int64 id, global::System.String profile)
        {
            Order order = new Order();
            order.Id = id;
            order.Profile = profile;
            return order;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Currency
        {
            get
            {
                return _Currency;
            }
            set
            {
                OnCurrencyChanging(value);
                ReportPropertyChanging("Currency");
                _Currency = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Currency");
                OnCurrencyChanged();
            }
        }
        private global::System.String _Currency;
        partial void OnCurrencyChanging(global::System.String value);
        partial void OnCurrencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private Nullable<global::System.Decimal> _Total;
        partial void OnTotalChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SWRegLinkForReceipt
        {
            get
            {
                return _SWRegLinkForReceipt;
            }
            set
            {
                OnSWRegLinkForReceiptChanging(value);
                ReportPropertyChanging("SWRegLinkForReceipt");
                _SWRegLinkForReceipt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SWRegLinkForReceipt");
                OnSWRegLinkForReceiptChanged();
            }
        }
        private global::System.String _SWRegLinkForReceipt;
        partial void OnSWRegLinkForReceiptChanging(global::System.String value);
        partial void OnSWRegLinkForReceiptChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SWRegOrderNumber
        {
            get
            {
                return _SWRegOrderNumber;
            }
            set
            {
                OnSWRegOrderNumberChanging(value);
                ReportPropertyChanging("SWRegOrderNumber");
                _SWRegOrderNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SWRegOrderNumber");
                OnSWRegOrderNumberChanged();
            }
        }
        private global::System.String _SWRegOrderNumber;
        partial void OnSWRegOrderNumberChanging(global::System.String value);
        partial void OnSWRegOrderNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Vat
        {
            get
            {
                return _Vat;
            }
            set
            {
                OnVatChanging(value);
                ReportPropertyChanging("Vat");
                _Vat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Vat");
                OnVatChanged();
            }
        }
        private Nullable<global::System.Decimal> _Vat;
        partial void OnVatChanging(Nullable<global::System.Decimal> value);
        partial void OnVatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UniqueOrderId
        {
            get
            {
                return _UniqueOrderId;
            }
            set
            {
                OnUniqueOrderIdChanging(value);
                ReportPropertyChanging("UniqueOrderId");
                _UniqueOrderId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UniqueOrderId");
                OnUniqueOrderIdChanged();
            }
        }
        private global::System.String _UniqueOrderId;
        partial void OnUniqueOrderIdChanging(global::System.String value);
        partial void OnUniqueOrderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LicenseQuantity
        {
            get
            {
                return _LicenseQuantity;
            }
            set
            {
                OnLicenseQuantityChanging(value);
                ReportPropertyChanging("LicenseQuantity");
                _LicenseQuantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LicenseQuantity");
                OnLicenseQuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _LicenseQuantity;
        partial void OnLicenseQuantityChanging(Nullable<global::System.Int32> value);
        partial void OnLicenseQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> OrderDate
        {
            get
            {
                return _OrderDate;
            }
            set
            {
                OnOrderDateChanging(value);
                ReportPropertyChanging("OrderDate");
                _OrderDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderDate");
                OnOrderDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _OrderDate;
        partial void OnOrderDateChanging(Nullable<global::System.DateTime> value);
        partial void OnOrderDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> BuyerId
        {
            get
            {
                return _BuyerId;
            }
            set
            {
                OnBuyerIdChanging(value);
                ReportPropertyChanging("BuyerId");
                _BuyerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BuyerId");
                OnBuyerIdChanged();
            }
        }
        private Nullable<global::System.Int64> _BuyerId;
        partial void OnBuyerIdChanging(Nullable<global::System.Int64> value);
        partial void OnBuyerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Profile
        {
            get
            {
                return _Profile;
            }
            set
            {
                OnProfileChanging(value);
                ReportPropertyChanging("Profile");
                _Profile = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Profile");
                OnProfileChanged();
            }
        }
        private global::System.String _Profile;
        partial void OnProfileChanging(global::System.String value);
        partial void OnProfileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OrderType
        {
            get
            {
                return _OrderType;
            }
            set
            {
                OnOrderTypeChanging(value);
                ReportPropertyChanging("OrderType");
                _OrderType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderType");
                OnOrderTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _OrderType;
        partial void OnOrderTypeChanging(Nullable<global::System.Int32> value);
        partial void OnOrderTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PlimusLinkForReceipt
        {
            get
            {
                return _PlimusLinkForReceipt;
            }
            set
            {
                OnPlimusLinkForReceiptChanging(value);
                ReportPropertyChanging("PlimusLinkForReceipt");
                _PlimusLinkForReceipt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PlimusLinkForReceipt");
                OnPlimusLinkForReceiptChanged();
            }
        }
        private global::System.String _PlimusLinkForReceipt;
        partial void OnPlimusLinkForReceiptChanging(global::System.String value);
        partial void OnPlimusLinkForReceiptChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PlimusOrderNumber
        {
            get
            {
                return _PlimusOrderNumber;
            }
            set
            {
                OnPlimusOrderNumberChanging(value);
                ReportPropertyChanging("PlimusOrderNumber");
                _PlimusOrderNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PlimusOrderNumber");
                OnPlimusOrderNumberChanged();
            }
        }
        private global::System.String _PlimusOrderNumber;
        partial void OnPlimusOrderNumberChanging(global::System.String value);
        partial void OnPlimusOrderNumberChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("UberProf.BackendModel", "FK318A099B6965C307", "Buyers")]
        public Buyer Buyer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Buyer>("UberProf.BackendModel.FK318A099B6965C307", "Buyers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Buyer>("UberProf.BackendModel.FK318A099B6965C307", "Buyers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Buyer> BuyerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Buyer>("UberProf.BackendModel.FK318A099B6965C307", "Buyers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Buyer>("UberProf.BackendModel.FK318A099B6965C307", "Buyers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("UberProf.BackendModel", "FK570785C186B03BAA", "Buyers")]
        public Buyer Buyer1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Buyer>("UberProf.BackendModel.FK570785C186B03BAA", "Buyers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Buyer>("UberProf.BackendModel.FK570785C186B03BAA", "Buyers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Buyer> Buyer1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Buyer>("UberProf.BackendModel.FK570785C186B03BAA", "Buyers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Buyer>("UberProf.BackendModel.FK570785C186B03BAA", "Buyers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("UberProf.BackendModel", "FK3A420F9C2AB61060", "LicenseFiles")]
        public EntityCollection<LicenseFile> LicenseFiles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<LicenseFile>("UberProf.BackendModel.FK3A420F9C2AB61060", "LicenseFiles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<LicenseFile>("UberProf.BackendModel.FK3A420F9C2AB61060", "LicenseFiles", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UberProf.BackendModel", Name="Prospect")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Prospect : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Prospect object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="profile">Initial value of the Profile property.</param>
        public static Prospect CreateProspect(global::System.Int64 id, global::System.String profile)
        {
            Prospect prospect = new Prospect();
            prospect.Id = id;
            prospect.Profile = profile;
            return prospect;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyName
        {
            get
            {
                return _CompanyName;
            }
            set
            {
                OnCompanyNameChanging(value);
                ReportPropertyChanging("CompanyName");
                _CompanyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyName");
                OnCompanyNameChanged();
            }
        }
        private global::System.String _CompanyName;
        partial void OnCompanyNameChanging(global::System.String value);
        partial void OnCompanyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> TrackingId
        {
            get
            {
                return _TrackingId;
            }
            set
            {
                OnTrackingIdChanging(value);
                ReportPropertyChanging("TrackingId");
                _TrackingId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TrackingId");
                OnTrackingIdChanged();
            }
        }
        private Nullable<global::System.Guid> _TrackingId;
        partial void OnTrackingIdChanging(Nullable<global::System.Guid> value);
        partial void OnTrackingIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                OnFullNameChanging(value);
                ReportPropertyChanging("FullName");
                _FullName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FullName");
                OnFullNameChanged();
            }
        }
        private global::System.String _FullName;
        partial void OnFullNameChanging(global::System.String value);
        partial void OnFullNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Profile
        {
            get
            {
                return _Profile;
            }
            set
            {
                OnProfileChanging(value);
                ReportPropertyChanging("Profile");
                _Profile = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Profile");
                OnProfileChanged();
            }
        }
        private global::System.String _Profile;
        partial void OnProfileChanging(global::System.String value);
        partial void OnProfileChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UberProf.BackendModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UberProf.BackendModel", Name="Trial")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Trial : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Trial object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="profile">Initial value of the Profile property.</param>
        public static Trial CreateTrial(global::System.Guid id, global::System.String profile)
        {
            Trial trial = new Trial();
            trial.Id = id;
            trial.Profile = profile;
            return trial;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Expiry
        {
            get
            {
                return _Expiry;
            }
            set
            {
                OnExpiryChanging(value);
                ReportPropertyChanging("Expiry");
                _Expiry = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Expiry");
                OnExpiryChanged();
            }
        }
        private Nullable<global::System.DateTime> _Expiry;
        partial void OnExpiryChanging(Nullable<global::System.DateTime> value);
        partial void OnExpiryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Company
        {
            get
            {
                return _Company;
            }
            set
            {
                OnCompanyChanging(value);
                ReportPropertyChanging("Company");
                _Company = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Company");
                OnCompanyChanged();
            }
        }
        private global::System.String _Company;
        partial void OnCompanyChanging(global::System.String value);
        partial void OnCompanyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> TrackingId
        {
            get
            {
                return _TrackingId;
            }
            set
            {
                OnTrackingIdChanging(value);
                ReportPropertyChanging("TrackingId");
                _TrackingId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TrackingId");
                OnTrackingIdChanged();
            }
        }
        private Nullable<global::System.Guid> _TrackingId;
        partial void OnTrackingIdChanging(Nullable<global::System.Guid> value);
        partial void OnTrackingIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Profile
        {
            get
            {
                return _Profile;
            }
            set
            {
                OnProfileChanging(value);
                ReportPropertyChanging("Profile");
                _Profile = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Profile");
                OnProfileChanged();
            }
        }
        private global::System.String _Profile;
        partial void OnProfileChanging(global::System.String value);
        partial void OnProfileChanged();

        #endregion
    
    }

    #endregion
    
}
